global:
  scrape_interval: 15s  #全局抓取间隔
  scrape_timeout: 10s  #全局抓取超时时间    
  evaluation_interval: 15s  #全局评估间隔

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
    scheme: http
    timeout: 10s

rule_files:
    - '/etc/prometheus/rules/*.yml'
    - '/etc/prometheus/rules/*.yaml'
    - '/etc/prometheus/rules/*.rules'

scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  static_configs:
  - targets: 
    - localhost:9090
    labels:
      instance: prometheus

- job_name: alertmanager
  scrape_interval: 15s
  static_configs:
  - targets:
    - alertmanager:9093
    labels:
      instance: alertmanager

- job_name: pushgateway
  scrape_interval: 15s
  static_configs:
  - targets:
    - pushgateway:9091
    labels:
      instance: pushgateway

- job_name: node
  scrape_interval: 30s
  static_configs:
  - targets:
    - node-exporter:9100
    labels:
      instance: node

- job_name: 'cadvisor'
  scrape_interval: 15s
  static_configs:
  - targets: ['cadvisor:8080']

- job_name: 'mysqld'
  scrape_interval: 15s
  static_configs:
  - targets: ['mysqld-exporter:9104']
    labels:
      instance: mysql

- job_name: kafka
  scrape_interval: 15s
  static_configs:
  - targets: ['kafka-exporter:9308']
    labels:
      instance: kafka

- job_name: redis
  scrape_interval: 15s
  static_configs:
  - targets: ['redis-exporter:9121']
    labels:
      instance: redis

- job_name: iotdb
  scrape_interval: 15s
  static_configs:
  - targets: ['8.130.140.140:9091']
    labels:
      instance: iotdb

- job_name: clickhouse
  scrape_interval: 15s
  static_configs:
  - targets: ['8.130.140.140:9363']
    labels:
      instance: clickhouse

