version: '3'

services:
  cli-exporter:
    image: 
    container_name: mysqld-exporter 
    #links:
    #  - 'my_mysql_container:bdd'
    environment:
      - 'DATA_SOURCE_NAME=root:1234qwer@(172.16.20.140:3306)/'
    networks:
      - monitor
    depends_on:
      - prometheus
    restart: always

