version: '3'

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter 
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|etc|run|host)($$|/)'
    expose:
      - '9100'
    networks:
      - monitor
    #depends_on:
    #  - prometheus
    restart: always

networks:
  monitor:
    name: prometheus-docker-compose_monitor
    external: true

