version: '3'

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter 
    volumes:
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
    expose:
      - '9100'
    networks:
      - monitor
    #depends_on:
    #  - prometheus
    restart: always

networks:
  monitor:
    name: prometheus-docker-compose_monitor
    external: true

