version: '3'

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter 
    volumes:
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
    networks:
      - monitor
    depends_on:
      - prometheus
    restart: always

