version: '3'

services:
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter 
    volumes:
      - /:/host/root:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command: 
      - '--web.listen-address=0.0.0.0:19100'
      - '--path.rootfs=/host/root'
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--no-collector.wifi'
      - '--no-collector.hwmon'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|run)($$|/)'
    expose:
      - '9100'
    network_mode: host
    pid: host
    #networks:
    #  - monitor
    #depends_on:
    #  - prometheus
    restart: always

networks:
  monitor:
    name: prometheus-docker-compose_monitor
    external: true

