groups:

- name: '监控组件规则'
  rules:

    - alert: Prometheus状态
      expr: 'absent(up{job="prometheus"})'
      for: 0m
      labels:
        severity: 普通告警
      annotations:
        summary: Prometheus服务丢失
        description: "Prometheus服务丢失 <br/> 实例：{{ $labels.instance }}"

    - alert: 主机状态 
      expr: 'up == 0'
      for: 0m
      labels:
        severity: 严重告警
      annotations:
        summary: 主机宕机
        description: "主机宕机 <br/> 实例 {{ $labels.instance }}"

    - alert: Prometheus配置加载失败
      expr: 'prometheus_config_last_reload_successful != 1'
      for: 2m
      labels:
        severity: 普通告警
      annotations:
        summary: Prometheus 配置加载失败
        description: "Prometheus 配置重新加载错误 <br/> 实例：{{ $labels.instance }}"

    - alert: 监控组件多次重启
      expr: 'changes(process_start_time_seconds{job=~"prometheus|pushgateway|alertmanager"}[15m]) > 2'
      for: 0m
      labels:
        severity: 普通告警
      annotations:
        summary: 监控组件多次重新启动
        description: "组件在15分钟内已经重新启动2次以上 <br/> 实例：{{ $labels.instance }} "

    - alert: Alertmanager状态
      expr: 'absent(up{job="alertmanager"})'
      for: 0m
      labels:
        severity: 普通告警
      annotations:
        summary: AlertManager服务丢失
        description: "AlertManager服务丢失 <br/> 实例：{{ $labels.instance }}"

    - alert: Alertmanager配置加载失败
      expr: 'alertmanager_config_last_reload_successful != 1'
      for: 0m
      labels:
        severity: 普通告警
      annotations:
        summary: AlertManager 配置重新加载错误
        description: "AlertManager 配置重新加载失败 <br/> 实例：{{ $labels.instance }}"

    - alert: Prometheus不能连接到Alertmanager
      expr: 'prometheus_notifications_alertmanagers_discovered < 1'
      for: 0m
      labels:
        severity: 普通告警
      annotations:
        summary: Prometheus 不能连接到 Alertmanager
        description: "Prometheus不能和alertmanager通信 <br/> 实例：{{ $labels.instance }}  "

    - alert: Prometheus告警规则文件评估
      expr: 'increase(prometheus_rule_evaluation_failures_total[3m]) > 0'
      for: 2m
      labels:
        severity: 普通告警
      annotations:
        summary: Prometheus rule评估失败
        description: "Prometheus{{ $value }}条规则验证失败, 可能导致告警被忽略 <br/> 规则配置文件：{{$labels.rule_group}}"

    - alert: Prometheus规则评估速度
      expr: 'prometheus_rule_group_last_duration_seconds > prometheus_rule_group_interval_seconds'
      for: 5m
      labels:
        severity: 普通告警
      annotations:
        summary: Prometheus rule评估速度慢
        description: "Prometheus规则评估所花费的时间超过了预定的间隔。表明存储后端访问较慢或查询过于复杂 <br/> 规则配置文件：{{$labels.rule_group}}"

    - alert: Alertmanager发送通知失败
      expr: 'rate(alertmanager_notifications_failed_total[1m]) > 0'
      for: 0m
      labels:
        severity: 严重告警
      annotations:
        summary: AlertManager发送通知失败
        description: "Alertmanager失败发送通知 <br/> 实例：{{ $labels.instance }} <br/> 集成告警：{{$labels.integration}}"


